import Head from "next/head"
import Script from 'next/script'
import { __html } from "../js/material-kit"

const LayoutAuthencation = ({ children, ...props }: any) => {
    
    return (
        <>

            <Script id="gtm-script" type="text/javascript" dangerouslySetInnerHTML={{ __html }} ></Script>

            <Head>
                <title>{ props?.title || "Admin | Login" }</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />

            </Head>
            <div className="sign-in-basic">
                <div className="page-header align-items-start min-vh-100" 
                 style={{
                    backgroundImage: `url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80')`
                 }}
                >
                    <span className="mask bg-gradient-dark opacity-6"></span>
                    <div className="container my-auto" id="banner">
                        <div className="row">
                            <div className="col-lg-4 col-md-8 col-12 mx-auto">
                               { children }
                            </div>
                        </div>
                    </div>
                    <footer className="footer position-absolute bottom-2 py-2 w-100">
                        <div className="container">
                            <div className="row align-items-center justify-content-lg-between">
                                <div className="col-12 col-md-6 my-auto">
                                    <div className="copyright text-center text-sm text-white text-lg-start"></div>
                                </div>
                                <div className="col-12 col-md-6">
                                    {/* <ul className="nav nav-footer justify-content-center justify-content-lg-end">
                                        <li className="nav-item">
                                            <a href="https://www.creative-tim.com" className="nav-link text-white" target="_blank">Creative Tim</a>
                                        </li>
                                        <li className="nav-item">
                                            <a href="https://www.creative-tim.com/presentation" className="nav-link text-white" target="_blank">About Us</a>
                                        </li>
                                        <li className="nav-item">
                                            <a href="https://www.creative-tim.com/blog" className="nav-link text-white" target="_blank">Blog</a>
                                        </li>
                                        <li className="nav-item">
                                            <a href="https://www.creative-tim.com/license" className="nav-link pe-0 text-white" target="_blank">License</a>
                                        </li>
                                    </ul> */}
                                </div>
                            </div>
                        </div>
                    </footer>
                </div>
            </div>
        </>
    )
}

export default LayoutAuthencation